// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HelloRequest 请求数据格式
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_5ab21b4eb42d13ed, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// HelloReply 响应数据格式
type HelloReply struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_5ab21b4eb42d13ed, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type RetrievalRepoRequest struct {
	JobId                int32    `protobuf:"varint,1,opt,name=jobId,proto3" json:"jobId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievalRepoRequest) Reset()         { *m = RetrievalRepoRequest{} }
func (m *RetrievalRepoRequest) String() string { return proto.CompactTextString(m) }
func (*RetrievalRepoRequest) ProtoMessage()    {}
func (*RetrievalRepoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_5ab21b4eb42d13ed, []int{2}
}
func (m *RetrievalRepoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalRepoRequest.Unmarshal(m, b)
}
func (m *RetrievalRepoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalRepoRequest.Marshal(b, m, deterministic)
}
func (dst *RetrievalRepoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalRepoRequest.Merge(dst, src)
}
func (m *RetrievalRepoRequest) XXX_Size() int {
	return xxx_messageInfo_RetrievalRepoRequest.Size(m)
}
func (m *RetrievalRepoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalRepoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalRepoRequest proto.InternalMessageInfo

func (m *RetrievalRepoRequest) GetJobId() int32 {
	if m != nil {
		return m.JobId
	}
	return 0
}

type RetrievalRepoResponse struct {
	RepoId               int32    `protobuf:"varint,1,opt,name=repoId,proto3" json:"repoId,omitempty"`
	RepoName             string   `protobuf:"bytes,2,opt,name=repoName,proto3" json:"repoName,omitempty"`
	PersonUuid           string   `protobuf:"bytes,3,opt,name=personUuid,proto3" json:"personUuid,omitempty"`
	IdentityNumber       string   `protobuf:"bytes,4,opt,name=identityNumber,proto3" json:"identityNumber,omitempty"`
	Age                  int32    `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RetrievalRepoResponse) Reset()         { *m = RetrievalRepoResponse{} }
func (m *RetrievalRepoResponse) String() string { return proto.CompactTextString(m) }
func (*RetrievalRepoResponse) ProtoMessage()    {}
func (*RetrievalRepoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_5ab21b4eb42d13ed, []int{3}
}
func (m *RetrievalRepoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RetrievalRepoResponse.Unmarshal(m, b)
}
func (m *RetrievalRepoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RetrievalRepoResponse.Marshal(b, m, deterministic)
}
func (dst *RetrievalRepoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RetrievalRepoResponse.Merge(dst, src)
}
func (m *RetrievalRepoResponse) XXX_Size() int {
	return xxx_messageInfo_RetrievalRepoResponse.Size(m)
}
func (m *RetrievalRepoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RetrievalRepoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RetrievalRepoResponse proto.InternalMessageInfo

func (m *RetrievalRepoResponse) GetRepoId() int32 {
	if m != nil {
		return m.RepoId
	}
	return 0
}

func (m *RetrievalRepoResponse) GetRepoName() string {
	if m != nil {
		return m.RepoName
	}
	return ""
}

func (m *RetrievalRepoResponse) GetPersonUuid() string {
	if m != nil {
		return m.PersonUuid
	}
	return ""
}

func (m *RetrievalRepoResponse) GetIdentityNumber() string {
	if m != nil {
		return m.IdentityNumber
	}
	return ""
}

func (m *RetrievalRepoResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "proto.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "proto.HelloReply")
	proto.RegisterType((*RetrievalRepoRequest)(nil), "proto.RetrievalRepoRequest")
	proto.RegisterType((*RetrievalRepoResponse)(nil), "proto.RetrievalRepoResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/proto.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

// RetrievalClient is the client API for Retrieval service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RetrievalClient interface {
	RetrievalRepo(ctx context.Context, in *RetrievalRepoRequest, opts ...grpc.CallOption) (*RetrievalRepoResponse, error)
}

type retrievalClient struct {
	cc *grpc.ClientConn
}

func NewRetrievalClient(cc *grpc.ClientConn) RetrievalClient {
	return &retrievalClient{cc}
}

func (c *retrievalClient) RetrievalRepo(ctx context.Context, in *RetrievalRepoRequest, opts ...grpc.CallOption) (*RetrievalRepoResponse, error) {
	out := new(RetrievalRepoResponse)
	err := c.cc.Invoke(ctx, "/proto.Retrieval/RetrievalRepo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RetrievalServer is the server API for Retrieval service.
type RetrievalServer interface {
	RetrievalRepo(context.Context, *RetrievalRepoRequest) (*RetrievalRepoResponse, error)
}

func RegisterRetrievalServer(s *grpc.Server, srv RetrievalServer) {
	s.RegisterService(&_Retrieval_serviceDesc, srv)
}

func _Retrieval_RetrievalRepo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RetrievalRepoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RetrievalServer).RetrievalRepo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Retrieval/RetrievalRepo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RetrievalServer).RetrievalRepo(ctx, req.(*RetrievalRepoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Retrieval_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Retrieval",
	HandlerType: (*RetrievalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RetrievalRepo",
			Handler:    _Retrieval_RetrievalRepo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "test.proto",
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_test_5ab21b4eb42d13ed) }

var fileDescriptor_test_5ab21b4eb42d13ed = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x50, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x6d, 0xbe, 0x36, 0xfd, 0x39, 0x7c, 0x8a, 0x5e, 0xab, 0x84, 0x28, 0x22, 0xb3, 0x28, 0x2e,
	0xa4, 0x8b, 0xea, 0xde, 0xa5, 0x0a, 0xd2, 0x45, 0xc4, 0x85, 0xcb, 0x84, 0x5c, 0x24, 0x92, 0x64,
	0xc6, 0x99, 0x89, 0x90, 0x07, 0xf2, 0x3d, 0x25, 0x93, 0x34, 0xb4, 0xa5, 0xab, 0xdc, 0xf3, 0x73,
	0x73, 0xe7, 0x1c, 0xc0, 0xb2, 0xb1, 0x4b, 0xa5, 0xa5, 0x95, 0xe4, 0xbb, 0x8f, 0x10, 0xf8, 0xff,
	0xcc, 0x79, 0x2e, 0x23, 0xfe, 0xae, 0xd8, 0x58, 0x22, 0x8c, 0xca, 0xb8, 0xe0, 0xc0, 0xbb, 0xf1,
	0x6e, 0x67, 0x91, 0x9b, 0xc5, 0x02, 0xe8, 0x3c, 0x2a, 0xaf, 0x29, 0xc0, 0xa4, 0x60, 0x63, 0xe2,
	0xcf, 0x8d, 0x69, 0x03, 0xc5, 0x1d, 0xe6, 0x11, 0x5b, 0x9d, 0xf1, 0x4f, 0x9c, 0x47, 0xac, 0xfa,
	0x7f, 0xce, 0xe1, 0x7f, 0xc9, 0xe4, 0x25, 0x75, 0x7e, 0x3f, 0x6a, 0x81, 0xf8, 0xf5, 0x70, 0xbe,
	0x67, 0x37, 0x4a, 0x96, 0x86, 0xe9, 0x02, 0x63, 0xcd, 0x4a, 0xf6, 0x0b, 0x1d, 0xa2, 0x10, 0xd3,
	0x66, 0x5a, 0x37, 0xef, 0xfb, 0xe7, 0x4e, 0xf7, 0x98, 0xae, 0x01, 0xc5, 0xda, 0xc8, 0xf2, 0xbd,
	0xca, 0xd2, 0x60, 0xe8, 0xd4, 0x2d, 0x86, 0x16, 0x38, 0xce, 0x52, 0x2e, 0x6d, 0x66, 0xeb, 0x75,
	0x55, 0x24, 0xac, 0x83, 0x91, 0xf3, 0xec, 0xb1, 0x74, 0x82, 0x61, 0x93, 0xcc, 0x77, 0x87, 0x9b,
	0x71, 0xf5, 0x88, 0xc9, 0x93, 0x66, 0xb6, 0xac, 0xe9, 0x01, 0xd3, 0xb7, 0xb8, 0x76, 0x5d, 0xd0,
	0x59, 0xdb, 0xe3, 0x72, 0xbb, 0xbd, 0xf0, 0x74, 0x97, 0x54, 0x79, 0x2d, 0x06, 0xab, 0x0f, 0xcc,
	0xfa, 0x9c, 0xf4, 0x8a, 0xa3, 0x9d, 0xd0, 0x74, 0xd9, 0xad, 0x1c, 0x6a, 0x2e, 0xbc, 0x3a, 0x2c,
	0xb6, 0x3d, 0x89, 0x41, 0x32, 0x76, 0xf2, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x66, 0x03,
	0xf1, 0xc8, 0xd9, 0x01, 0x00, 0x00,
}
