// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lynxi.proto

package Lynxi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 启动 pipeline 的参数
// 不同 pipeline 定义自己的 pipelineRequestContent。
type PipelineRequest struct {
	PipelineName string `protobuf:"bytes,1,opt,name=pipelineName,proto3" json:"pipelineName,omitempty"`
	DeviceDesc   uint32 `protobuf:"varint,2,opt,name=deviceDesc,proto3" json:"deviceDesc,omitempty"`
	// Types that are valid to be assigned to PipelineRequestContent:
	//	*PipelineRequest_FrameExtractFrequency
	PipelineRequestContent isPipelineRequest_PipelineRequestContent `protobuf_oneof:"pipelineRequestContent"`
	XXX_NoUnkeyedLiteral   struct{}                                 `json:"-"`
	XXX_unrecognized       []byte                                   `json:"-"`
	XXX_sizecache          int32                                    `json:"-"`
}

func (m *PipelineRequest) Reset()         { *m = PipelineRequest{} }
func (m *PipelineRequest) String() string { return proto.CompactTextString(m) }
func (*PipelineRequest) ProtoMessage()    {}
func (*PipelineRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{0}
}
func (m *PipelineRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineRequest.Unmarshal(m, b)
}
func (m *PipelineRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineRequest.Marshal(b, m, deterministic)
}
func (dst *PipelineRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineRequest.Merge(dst, src)
}
func (m *PipelineRequest) XXX_Size() int {
	return xxx_messageInfo_PipelineRequest.Size(m)
}
func (m *PipelineRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineRequest proto.InternalMessageInfo

func (m *PipelineRequest) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

func (m *PipelineRequest) GetDeviceDesc() uint32 {
	if m != nil {
		return m.DeviceDesc
	}
	return 0
}

type isPipelineRequest_PipelineRequestContent interface {
	isPipelineRequest_PipelineRequestContent()
}

type PipelineRequest_FrameExtractFrequency struct {
	FrameExtractFrequency *FrameExtractFrequency `protobuf:"bytes,3,opt,name=frameExtractFrequency,proto3,oneof"`
}

func (*PipelineRequest_FrameExtractFrequency) isPipelineRequest_PipelineRequestContent() {}

func (m *PipelineRequest) GetPipelineRequestContent() isPipelineRequest_PipelineRequestContent {
	if m != nil {
		return m.PipelineRequestContent
	}
	return nil
}

func (m *PipelineRequest) GetFrameExtractFrequency() *FrameExtractFrequency {
	if x, ok := m.GetPipelineRequestContent().(*PipelineRequest_FrameExtractFrequency); ok {
		return x.FrameExtractFrequency
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PipelineRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PipelineRequest_OneofMarshaler, _PipelineRequest_OneofUnmarshaler, _PipelineRequest_OneofSizer, []interface{}{
		(*PipelineRequest_FrameExtractFrequency)(nil),
	}
}

func _PipelineRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PipelineRequest)
	// pipelineRequestContent
	switch x := m.PipelineRequestContent.(type) {
	case *PipelineRequest_FrameExtractFrequency:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.FrameExtractFrequency); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PipelineRequest.PipelineRequestContent has unexpected type %T", x)
	}
	return nil
}

func _PipelineRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PipelineRequest)
	switch tag {
	case 3: // pipelineRequestContent.frameExtractFrequency
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FrameExtractFrequency)
		err := b.DecodeMessage(msg)
		m.PipelineRequestContent = &PipelineRequest_FrameExtractFrequency{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PipelineRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PipelineRequest)
	// pipelineRequestContent
	switch x := m.PipelineRequestContent.(type) {
	case *PipelineRequest_FrameExtractFrequency:
		s := proto.Size(x.FrameExtractFrequency)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type FrameExtractFrequency struct {
	Pose                 uint32   `protobuf:"varint,1,opt,name=Pose,proto3" json:"Pose,omitempty"`
	Detect               uint32   `protobuf:"varint,2,opt,name=Detect,proto3" json:"Detect,omitempty"`
	Face                 uint32   `protobuf:"varint,3,opt,name=Face,proto3" json:"Face,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FrameExtractFrequency) Reset()         { *m = FrameExtractFrequency{} }
func (m *FrameExtractFrequency) String() string { return proto.CompactTextString(m) }
func (*FrameExtractFrequency) ProtoMessage()    {}
func (*FrameExtractFrequency) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{1}
}
func (m *FrameExtractFrequency) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FrameExtractFrequency.Unmarshal(m, b)
}
func (m *FrameExtractFrequency) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FrameExtractFrequency.Marshal(b, m, deterministic)
}
func (dst *FrameExtractFrequency) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FrameExtractFrequency.Merge(dst, src)
}
func (m *FrameExtractFrequency) XXX_Size() int {
	return xxx_messageInfo_FrameExtractFrequency.Size(m)
}
func (m *FrameExtractFrequency) XXX_DiscardUnknown() {
	xxx_messageInfo_FrameExtractFrequency.DiscardUnknown(m)
}

var xxx_messageInfo_FrameExtractFrequency proto.InternalMessageInfo

func (m *FrameExtractFrequency) GetPose() uint32 {
	if m != nil {
		return m.Pose
	}
	return 0
}

func (m *FrameExtractFrequency) GetDetect() uint32 {
	if m != nil {
		return m.Detect
	}
	return 0
}

func (m *FrameExtractFrequency) GetFace() uint32 {
	if m != nil {
		return m.Face
	}
	return 0
}

// pipeline 启动结果，可以包含每个 worker 的启动结果等详细信息
type PipelineReply struct {
	// Types that are valid to be assigned to PipelineReplyContent:
	//	*PipelineReply_Status
	PipelineReplyContent isPipelineReply_PipelineReplyContent `protobuf_oneof:"pipelineReplyContent"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *PipelineReply) Reset()         { *m = PipelineReply{} }
func (m *PipelineReply) String() string { return proto.CompactTextString(m) }
func (*PipelineReply) ProtoMessage()    {}
func (*PipelineReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{2}
}
func (m *PipelineReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PipelineReply.Unmarshal(m, b)
}
func (m *PipelineReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PipelineReply.Marshal(b, m, deterministic)
}
func (dst *PipelineReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PipelineReply.Merge(dst, src)
}
func (m *PipelineReply) XXX_Size() int {
	return xxx_messageInfo_PipelineReply.Size(m)
}
func (m *PipelineReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PipelineReply.DiscardUnknown(m)
}

var xxx_messageInfo_PipelineReply proto.InternalMessageInfo

type isPipelineReply_PipelineReplyContent interface {
	isPipelineReply_PipelineReplyContent()
}

type PipelineReply_Status struct {
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3,oneof"`
}

func (*PipelineReply_Status) isPipelineReply_PipelineReplyContent() {}

func (m *PipelineReply) GetPipelineReplyContent() isPipelineReply_PipelineReplyContent {
	if m != nil {
		return m.PipelineReplyContent
	}
	return nil
}

func (m *PipelineReply) GetStatus() *Status {
	if x, ok := m.GetPipelineReplyContent().(*PipelineReply_Status); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PipelineReply) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PipelineReply_OneofMarshaler, _PipelineReply_OneofUnmarshaler, _PipelineReply_OneofSizer, []interface{}{
		(*PipelineReply_Status)(nil),
	}
}

func _PipelineReply_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PipelineReply)
	// pipelineReplyContent
	switch x := m.PipelineReplyContent.(type) {
	case *PipelineReply_Status:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Status); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PipelineReply.PipelineReplyContent has unexpected type %T", x)
	}
	return nil
}

func _PipelineReply_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PipelineReply)
	switch tag {
	case 1: // pipelineReplyContent.status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Status)
		err := b.DecodeMessage(msg)
		m.PipelineReplyContent = &PipelineReply_Status{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PipelineReply_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PipelineReply)
	// pipelineReplyContent
	switch x := m.PipelineReplyContent.(type) {
	case *PipelineReply_Status:
		s := proto.Size(x.Status)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 执行任务的请求参数
type TaskRequest struct {
	TaskId       uint32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	PipelineName string `protobuf:"bytes,2,opt,name=pipelineName,proto3" json:"pipelineName,omitempty"`
	// Types that are valid to be assigned to TaskRequestContent:
	//	*TaskRequest_SmartClass
	TaskRequestContent   isTaskRequest_TaskRequestContent `protobuf_oneof:"taskRequestContent"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{3}
}
func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (dst *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(dst, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskRequest) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

type isTaskRequest_TaskRequestContent interface {
	isTaskRequest_TaskRequestContent()
}

type TaskRequest_SmartClass struct {
	SmartClass *SmartClassInfo `protobuf:"bytes,3,opt,name=smartClass,proto3,oneof"`
}

func (*TaskRequest_SmartClass) isTaskRequest_TaskRequestContent() {}

func (m *TaskRequest) GetTaskRequestContent() isTaskRequest_TaskRequestContent {
	if m != nil {
		return m.TaskRequestContent
	}
	return nil
}

func (m *TaskRequest) GetSmartClass() *SmartClassInfo {
	if x, ok := m.GetTaskRequestContent().(*TaskRequest_SmartClass); ok {
		return x.SmartClass
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TaskRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TaskRequest_OneofMarshaler, _TaskRequest_OneofUnmarshaler, _TaskRequest_OneofSizer, []interface{}{
		(*TaskRequest_SmartClass)(nil),
	}
}

func _TaskRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TaskRequest)
	// taskRequestContent
	switch x := m.TaskRequestContent.(type) {
	case *TaskRequest_SmartClass:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SmartClass); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TaskRequest.TaskRequestContent has unexpected type %T", x)
	}
	return nil
}

func _TaskRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TaskRequest)
	switch tag {
	case 3: // taskRequestContent.smartClass
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SmartClassInfo)
		err := b.DecodeMessage(msg)
		m.TaskRequestContent = &TaskRequest_SmartClass{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TaskRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TaskRequest)
	// taskRequestContent
	switch x := m.TaskRequestContent.(type) {
	case *TaskRequest_SmartClass:
		s := proto.Size(x.SmartClass)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type SmartClassInfo struct {
	ConfigFilePath       string   `protobuf:"bytes,1,opt,name=configFilePath,proto3" json:"configFilePath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmartClassInfo) Reset()         { *m = SmartClassInfo{} }
func (m *SmartClassInfo) String() string { return proto.CompactTextString(m) }
func (*SmartClassInfo) ProtoMessage()    {}
func (*SmartClassInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{4}
}
func (m *SmartClassInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmartClassInfo.Unmarshal(m, b)
}
func (m *SmartClassInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmartClassInfo.Marshal(b, m, deterministic)
}
func (dst *SmartClassInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmartClassInfo.Merge(dst, src)
}
func (m *SmartClassInfo) XXX_Size() int {
	return xxx_messageInfo_SmartClassInfo.Size(m)
}
func (m *SmartClassInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SmartClassInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SmartClassInfo proto.InternalMessageInfo

func (m *SmartClassInfo) GetConfigFilePath() string {
	if m != nil {
		return m.ConfigFilePath
	}
	return ""
}

// 任务执行结果
type TaskReply struct {
	TaskId uint32 `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	// Types that are valid to be assigned to TaskReplyContent:
	//	*TaskReply_SporadicData
	//	*TaskReply_PeriodicData
	//	*TaskReply_AudioData
	TaskReplyContent     isTaskReply_TaskReplyContent `protobuf_oneof:"taskReplyContent"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *TaskReply) Reset()         { *m = TaskReply{} }
func (m *TaskReply) String() string { return proto.CompactTextString(m) }
func (*TaskReply) ProtoMessage()    {}
func (*TaskReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{5}
}
func (m *TaskReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskReply.Unmarshal(m, b)
}
func (m *TaskReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskReply.Marshal(b, m, deterministic)
}
func (dst *TaskReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskReply.Merge(dst, src)
}
func (m *TaskReply) XXX_Size() int {
	return xxx_messageInfo_TaskReply.Size(m)
}
func (m *TaskReply) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskReply.DiscardUnknown(m)
}

var xxx_messageInfo_TaskReply proto.InternalMessageInfo

func (m *TaskReply) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

type isTaskReply_TaskReplyContent interface {
	isTaskReply_TaskReplyContent()
}

type TaskReply_SporadicData struct {
	SporadicData *SporadicStreamDataReply `protobuf:"bytes,2,opt,name=sporadicData,proto3,oneof"`
}

type TaskReply_PeriodicData struct {
	PeriodicData *PeriodicStreamDataReply `protobuf:"bytes,3,opt,name=periodicData,proto3,oneof"`
}

type TaskReply_AudioData struct {
	AudioData *AudioStreamDataReply `protobuf:"bytes,4,opt,name=audioData,proto3,oneof"`
}

func (*TaskReply_SporadicData) isTaskReply_TaskReplyContent() {}

func (*TaskReply_PeriodicData) isTaskReply_TaskReplyContent() {}

func (*TaskReply_AudioData) isTaskReply_TaskReplyContent() {}

func (m *TaskReply) GetTaskReplyContent() isTaskReply_TaskReplyContent {
	if m != nil {
		return m.TaskReplyContent
	}
	return nil
}

func (m *TaskReply) GetSporadicData() *SporadicStreamDataReply {
	if x, ok := m.GetTaskReplyContent().(*TaskReply_SporadicData); ok {
		return x.SporadicData
	}
	return nil
}

func (m *TaskReply) GetPeriodicData() *PeriodicStreamDataReply {
	if x, ok := m.GetTaskReplyContent().(*TaskReply_PeriodicData); ok {
		return x.PeriodicData
	}
	return nil
}

func (m *TaskReply) GetAudioData() *AudioStreamDataReply {
	if x, ok := m.GetTaskReplyContent().(*TaskReply_AudioData); ok {
		return x.AudioData
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*TaskReply) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _TaskReply_OneofMarshaler, _TaskReply_OneofUnmarshaler, _TaskReply_OneofSizer, []interface{}{
		(*TaskReply_SporadicData)(nil),
		(*TaskReply_PeriodicData)(nil),
		(*TaskReply_AudioData)(nil),
	}
}

func _TaskReply_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*TaskReply)
	// taskReplyContent
	switch x := m.TaskReplyContent.(type) {
	case *TaskReply_SporadicData:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SporadicData); err != nil {
			return err
		}
	case *TaskReply_PeriodicData:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.PeriodicData); err != nil {
			return err
		}
	case *TaskReply_AudioData:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.AudioData); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("TaskReply.TaskReplyContent has unexpected type %T", x)
	}
	return nil
}

func _TaskReply_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*TaskReply)
	switch tag {
	case 2: // taskReplyContent.sporadicData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SporadicStreamDataReply)
		err := b.DecodeMessage(msg)
		m.TaskReplyContent = &TaskReply_SporadicData{msg}
		return true, err
	case 3: // taskReplyContent.periodicData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PeriodicStreamDataReply)
		err := b.DecodeMessage(msg)
		m.TaskReplyContent = &TaskReply_PeriodicData{msg}
		return true, err
	case 4: // taskReplyContent.audioData
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(AudioStreamDataReply)
		err := b.DecodeMessage(msg)
		m.TaskReplyContent = &TaskReply_AudioData{msg}
		return true, err
	default:
		return false, nil
	}
}

func _TaskReply_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*TaskReply)
	// taskReplyContent
	switch x := m.TaskReplyContent.(type) {
	case *TaskReply_SporadicData:
		s := proto.Size(x.SporadicData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TaskReply_PeriodicData:
		s := proto.Size(x.PeriodicData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case *TaskReply_AudioData:
		s := proto.Size(x.AudioData)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

// 停止请求(Request)
type StopRequest struct {
	TaskId               uint32   `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	PipelineName         string   `protobuf:"bytes,2,opt,name=pipelineName,proto3" json:"pipelineName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopRequest) Reset()         { *m = StopRequest{} }
func (m *StopRequest) String() string { return proto.CompactTextString(m) }
func (*StopRequest) ProtoMessage()    {}
func (*StopRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{6}
}
func (m *StopRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopRequest.Unmarshal(m, b)
}
func (m *StopRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopRequest.Marshal(b, m, deterministic)
}
func (dst *StopRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopRequest.Merge(dst, src)
}
func (m *StopRequest) XXX_Size() int {
	return xxx_messageInfo_StopRequest.Size(m)
}
func (m *StopRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopRequest proto.InternalMessageInfo

func (m *StopRequest) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *StopRequest) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

// 停止状态(Status)
type StopReply struct {
	Status               *Status  `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopReply) Reset()         { *m = StopReply{} }
func (m *StopReply) String() string { return proto.CompactTextString(m) }
func (*StopReply) ProtoMessage()    {}
func (*StopReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{7}
}
func (m *StopReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopReply.Unmarshal(m, b)
}
func (m *StopReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopReply.Marshal(b, m, deterministic)
}
func (dst *StopReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopReply.Merge(dst, src)
}
func (m *StopReply) XXX_Size() int {
	return xxx_messageInfo_StopReply.Size(m)
}
func (m *StopReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopReply proto.InternalMessageInfo

func (m *StopReply) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

// 偶发
type SporadicStreamDataReply struct {
	CamIdx               int32      `protobuf:"varint,1,opt,name=camIdx,proto3" json:"camIdx,omitempty"`
	FrameIdx             int32      `protobuf:"varint,2,opt,name=frameIdx,proto3" json:"frameIdx,omitempty"`
	TimeStamp            int64      `protobuf:"varint,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Image                []byte     `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	HandsUp              *HandsUp   `protobuf:"bytes,5,opt,name=handsUp,proto3" json:"handsUp,omitempty"`
	StandUp              *StandUp   `protobuf:"bytes,6,opt,name=standUp,proto3" json:"standUp,omitempty"`
	TeacherPatrol        *Patrol    `protobuf:"bytes,7,opt,name=teacherPatrol,proto3" json:"teacherPatrol,omitempty"`
	ProbSolve            *ProbSolve `protobuf:"bytes,8,opt,name=probSolve,proto3" json:"probSolve,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *SporadicStreamDataReply) Reset()         { *m = SporadicStreamDataReply{} }
func (m *SporadicStreamDataReply) String() string { return proto.CompactTextString(m) }
func (*SporadicStreamDataReply) ProtoMessage()    {}
func (*SporadicStreamDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{8}
}
func (m *SporadicStreamDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SporadicStreamDataReply.Unmarshal(m, b)
}
func (m *SporadicStreamDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SporadicStreamDataReply.Marshal(b, m, deterministic)
}
func (dst *SporadicStreamDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SporadicStreamDataReply.Merge(dst, src)
}
func (m *SporadicStreamDataReply) XXX_Size() int {
	return xxx_messageInfo_SporadicStreamDataReply.Size(m)
}
func (m *SporadicStreamDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SporadicStreamDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_SporadicStreamDataReply proto.InternalMessageInfo

func (m *SporadicStreamDataReply) GetCamIdx() int32 {
	if m != nil {
		return m.CamIdx
	}
	return 0
}

func (m *SporadicStreamDataReply) GetFrameIdx() int32 {
	if m != nil {
		return m.FrameIdx
	}
	return 0
}

func (m *SporadicStreamDataReply) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *SporadicStreamDataReply) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *SporadicStreamDataReply) GetHandsUp() *HandsUp {
	if m != nil {
		return m.HandsUp
	}
	return nil
}

func (m *SporadicStreamDataReply) GetStandUp() *StandUp {
	if m != nil {
		return m.StandUp
	}
	return nil
}

func (m *SporadicStreamDataReply) GetTeacherPatrol() *Patrol {
	if m != nil {
		return m.TeacherPatrol
	}
	return nil
}

func (m *SporadicStreamDataReply) GetProbSolve() *ProbSolve {
	if m != nil {
		return m.ProbSolve
	}
	return nil
}

// 举手
type HandsUp struct {
	Bbox                 []*BBox  `protobuf:"bytes,1,rep,name=bbox,proto3" json:"bbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HandsUp) Reset()         { *m = HandsUp{} }
func (m *HandsUp) String() string { return proto.CompactTextString(m) }
func (*HandsUp) ProtoMessage()    {}
func (*HandsUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{9}
}
func (m *HandsUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HandsUp.Unmarshal(m, b)
}
func (m *HandsUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HandsUp.Marshal(b, m, deterministic)
}
func (dst *HandsUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HandsUp.Merge(dst, src)
}
func (m *HandsUp) XXX_Size() int {
	return xxx_messageInfo_HandsUp.Size(m)
}
func (m *HandsUp) XXX_DiscardUnknown() {
	xxx_messageInfo_HandsUp.DiscardUnknown(m)
}

var xxx_messageInfo_HandsUp proto.InternalMessageInfo

func (m *HandsUp) GetBbox() []*BBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

// 站立
type StandUp struct {
	Bbox                 []*BBox  `protobuf:"bytes,1,rep,name=bbox,proto3" json:"bbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StandUp) Reset()         { *m = StandUp{} }
func (m *StandUp) String() string { return proto.CompactTextString(m) }
func (*StandUp) ProtoMessage()    {}
func (*StandUp) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{10}
}
func (m *StandUp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StandUp.Unmarshal(m, b)
}
func (m *StandUp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StandUp.Marshal(b, m, deterministic)
}
func (dst *StandUp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StandUp.Merge(dst, src)
}
func (m *StandUp) XXX_Size() int {
	return xxx_messageInfo_StandUp.Size(m)
}
func (m *StandUp) XXX_DiscardUnknown() {
	xxx_messageInfo_StandUp.DiscardUnknown(m)
}

var xxx_messageInfo_StandUp proto.InternalMessageInfo

func (m *StandUp) GetBbox() []*BBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

// 巡视
type Patrol struct {
	Bbox                 []*BBox  `protobuf:"bytes,1,rep,name=bbox,proto3" json:"bbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Patrol) Reset()         { *m = Patrol{} }
func (m *Patrol) String() string { return proto.CompactTextString(m) }
func (*Patrol) ProtoMessage()    {}
func (*Patrol) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{11}
}
func (m *Patrol) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Patrol.Unmarshal(m, b)
}
func (m *Patrol) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Patrol.Marshal(b, m, deterministic)
}
func (dst *Patrol) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Patrol.Merge(dst, src)
}
func (m *Patrol) XXX_Size() int {
	return xxx_messageInfo_Patrol.Size(m)
}
func (m *Patrol) XXX_DiscardUnknown() {
	xxx_messageInfo_Patrol.DiscardUnknown(m)
}

var xxx_messageInfo_Patrol proto.InternalMessageInfo

func (m *Patrol) GetBbox() []*BBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

// 讲题
type ProbSolve struct {
	Bbox                 []*BBox  `protobuf:"bytes,1,rep,name=bbox,proto3" json:"bbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProbSolve) Reset()         { *m = ProbSolve{} }
func (m *ProbSolve) String() string { return proto.CompactTextString(m) }
func (*ProbSolve) ProtoMessage()    {}
func (*ProbSolve) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{12}
}
func (m *ProbSolve) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProbSolve.Unmarshal(m, b)
}
func (m *ProbSolve) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProbSolve.Marshal(b, m, deterministic)
}
func (dst *ProbSolve) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProbSolve.Merge(dst, src)
}
func (m *ProbSolve) XXX_Size() int {
	return xxx_messageInfo_ProbSolve.Size(m)
}
func (m *ProbSolve) XXX_DiscardUnknown() {
	xxx_messageInfo_ProbSolve.DiscardUnknown(m)
}

var xxx_messageInfo_ProbSolve proto.InternalMessageInfo

func (m *ProbSolve) GetBbox() []*BBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

// 周期
type PeriodicStreamDataReply struct {
	CamIdx    int32      `protobuf:"varint,1,opt,name=camIdx,proto3" json:"camIdx,omitempty"`
	FrameIdx  int32      `protobuf:"varint,2,opt,name=frameIdx,proto3" json:"frameIdx,omitempty"`
	TimeStamp int64      `protobuf:"varint,3,opt,name=timeStamp,proto3" json:"timeStamp,omitempty"`
	Image     []byte     `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Emotion   []*Emotion `protobuf:"bytes,5,rep,name=emotion,proto3" json:"emotion,omitempty"`
	// Posture改成Attention.
	Attention            []*Attention `protobuf:"bytes,6,rep,name=attention,proto3" json:"attention,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *PeriodicStreamDataReply) Reset()         { *m = PeriodicStreamDataReply{} }
func (m *PeriodicStreamDataReply) String() string { return proto.CompactTextString(m) }
func (*PeriodicStreamDataReply) ProtoMessage()    {}
func (*PeriodicStreamDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{13}
}
func (m *PeriodicStreamDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeriodicStreamDataReply.Unmarshal(m, b)
}
func (m *PeriodicStreamDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeriodicStreamDataReply.Marshal(b, m, deterministic)
}
func (dst *PeriodicStreamDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeriodicStreamDataReply.Merge(dst, src)
}
func (m *PeriodicStreamDataReply) XXX_Size() int {
	return xxx_messageInfo_PeriodicStreamDataReply.Size(m)
}
func (m *PeriodicStreamDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PeriodicStreamDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_PeriodicStreamDataReply proto.InternalMessageInfo

func (m *PeriodicStreamDataReply) GetCamIdx() int32 {
	if m != nil {
		return m.CamIdx
	}
	return 0
}

func (m *PeriodicStreamDataReply) GetFrameIdx() int32 {
	if m != nil {
		return m.FrameIdx
	}
	return 0
}

func (m *PeriodicStreamDataReply) GetTimeStamp() int64 {
	if m != nil {
		return m.TimeStamp
	}
	return 0
}

func (m *PeriodicStreamDataReply) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

func (m *PeriodicStreamDataReply) GetEmotion() []*Emotion {
	if m != nil {
		return m.Emotion
	}
	return nil
}

func (m *PeriodicStreamDataReply) GetAttention() []*Attention {
	if m != nil {
		return m.Attention
	}
	return nil
}

// 音频流
type AudioStreamDataReply struct {
	StartTime            string   `protobuf:"bytes,1,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime              string   `protobuf:"bytes,2,opt,name=endTime,proto3" json:"endTime,omitempty"`
	SoundType            string   `protobuf:"bytes,3,opt,name=soundType,proto3" json:"soundType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AudioStreamDataReply) Reset()         { *m = AudioStreamDataReply{} }
func (m *AudioStreamDataReply) String() string { return proto.CompactTextString(m) }
func (*AudioStreamDataReply) ProtoMessage()    {}
func (*AudioStreamDataReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{14}
}
func (m *AudioStreamDataReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AudioStreamDataReply.Unmarshal(m, b)
}
func (m *AudioStreamDataReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AudioStreamDataReply.Marshal(b, m, deterministic)
}
func (dst *AudioStreamDataReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AudioStreamDataReply.Merge(dst, src)
}
func (m *AudioStreamDataReply) XXX_Size() int {
	return xxx_messageInfo_AudioStreamDataReply.Size(m)
}
func (m *AudioStreamDataReply) XXX_DiscardUnknown() {
	xxx_messageInfo_AudioStreamDataReply.DiscardUnknown(m)
}

var xxx_messageInfo_AudioStreamDataReply proto.InternalMessageInfo

func (m *AudioStreamDataReply) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *AudioStreamDataReply) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *AudioStreamDataReply) GetSoundType() string {
	if m != nil {
		return m.SoundType
	}
	return ""
}

// 表情
type Emotion struct {
	Bbox                 *BBox    `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Emotion              string   `protobuf:"bytes,2,opt,name=emotion,proto3" json:"emotion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Emotion) Reset()         { *m = Emotion{} }
func (m *Emotion) String() string { return proto.CompactTextString(m) }
func (*Emotion) ProtoMessage()    {}
func (*Emotion) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{15}
}
func (m *Emotion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Emotion.Unmarshal(m, b)
}
func (m *Emotion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Emotion.Marshal(b, m, deterministic)
}
func (dst *Emotion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Emotion.Merge(dst, src)
}
func (m *Emotion) XXX_Size() int {
	return xxx_messageInfo_Emotion.Size(m)
}
func (m *Emotion) XXX_DiscardUnknown() {
	xxx_messageInfo_Emotion.DiscardUnknown(m)
}

var xxx_messageInfo_Emotion proto.InternalMessageInfo

func (m *Emotion) GetBbox() *BBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *Emotion) GetEmotion() string {
	if m != nil {
		return m.Emotion
	}
	return ""
}

// 头部姿态
type Attention struct {
	Bbox                 *BBox    `protobuf:"bytes,1,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Attention            string   `protobuf:"bytes,2,opt,name=attention,proto3" json:"attention,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Attention) Reset()         { *m = Attention{} }
func (m *Attention) String() string { return proto.CompactTextString(m) }
func (*Attention) ProtoMessage()    {}
func (*Attention) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{16}
}
func (m *Attention) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Attention.Unmarshal(m, b)
}
func (m *Attention) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Attention.Marshal(b, m, deterministic)
}
func (dst *Attention) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attention.Merge(dst, src)
}
func (m *Attention) XXX_Size() int {
	return xxx_messageInfo_Attention.Size(m)
}
func (m *Attention) XXX_DiscardUnknown() {
	xxx_messageInfo_Attention.DiscardUnknown(m)
}

var xxx_messageInfo_Attention proto.InternalMessageInfo

func (m *Attention) GetBbox() *BBox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *Attention) GetAttention() string {
	if m != nil {
		return m.Attention
	}
	return ""
}

// 框 由原来的(x, y, w, h)改成现在的(x1, y1, x2, y2)
type BBox struct {
	Identity             string   `protobuf:"bytes,1,opt,name=identity,proto3" json:"identity,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	X1                   int32    `protobuf:"varint,3,opt,name=x1,proto3" json:"x1,omitempty"`
	Y1                   int32    `protobuf:"varint,4,opt,name=y1,proto3" json:"y1,omitempty"`
	X2                   int32    `protobuf:"varint,5,opt,name=x2,proto3" json:"x2,omitempty"`
	Y2                   int32    `protobuf:"varint,6,opt,name=y2,proto3" json:"y2,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BBox) Reset()         { *m = BBox{} }
func (m *BBox) String() string { return proto.CompactTextString(m) }
func (*BBox) ProtoMessage()    {}
func (*BBox) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{17}
}
func (m *BBox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BBox.Unmarshal(m, b)
}
func (m *BBox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BBox.Marshal(b, m, deterministic)
}
func (dst *BBox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BBox.Merge(dst, src)
}
func (m *BBox) XXX_Size() int {
	return xxx_messageInfo_BBox.Size(m)
}
func (m *BBox) XXX_DiscardUnknown() {
	xxx_messageInfo_BBox.DiscardUnknown(m)
}

var xxx_messageInfo_BBox proto.InternalMessageInfo

func (m *BBox) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *BBox) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *BBox) GetX1() int32 {
	if m != nil {
		return m.X1
	}
	return 0
}

func (m *BBox) GetY1() int32 {
	if m != nil {
		return m.Y1
	}
	return 0
}

func (m *BBox) GetX2() int32 {
	if m != nil {
		return m.X2
	}
	return 0
}

func (m *BBox) GetY2() int32 {
	if m != nil {
		return m.Y2
	}
	return 0
}

type ModifyRequest struct {
	PipelineName string `protobuf:"bytes,1,opt,name=pipelineName,proto3" json:"pipelineName,omitempty"`
	// Types that are valid to be assigned to ModifyRequestContent:
	//	*ModifyRequest_ShowControl
	ModifyRequestContent isModifyRequest_ModifyRequestContent `protobuf_oneof:"ModifyRequestContent"`
	XXX_NoUnkeyedLiteral struct{}                             `json:"-"`
	XXX_unrecognized     []byte                               `json:"-"`
	XXX_sizecache        int32                                `json:"-"`
}

func (m *ModifyRequest) Reset()         { *m = ModifyRequest{} }
func (m *ModifyRequest) String() string { return proto.CompactTextString(m) }
func (*ModifyRequest) ProtoMessage()    {}
func (*ModifyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{18}
}
func (m *ModifyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyRequest.Unmarshal(m, b)
}
func (m *ModifyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyRequest.Marshal(b, m, deterministic)
}
func (dst *ModifyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyRequest.Merge(dst, src)
}
func (m *ModifyRequest) XXX_Size() int {
	return xxx_messageInfo_ModifyRequest.Size(m)
}
func (m *ModifyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyRequest proto.InternalMessageInfo

func (m *ModifyRequest) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

type isModifyRequest_ModifyRequestContent interface {
	isModifyRequest_ModifyRequestContent()
}

type ModifyRequest_ShowControl struct {
	ShowControl *ShowControl `protobuf:"bytes,2,opt,name=showControl,proto3,oneof"`
}

func (*ModifyRequest_ShowControl) isModifyRequest_ModifyRequestContent() {}

func (m *ModifyRequest) GetModifyRequestContent() isModifyRequest_ModifyRequestContent {
	if m != nil {
		return m.ModifyRequestContent
	}
	return nil
}

func (m *ModifyRequest) GetShowControl() *ShowControl {
	if x, ok := m.GetModifyRequestContent().(*ModifyRequest_ShowControl); ok {
		return x.ShowControl
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ModifyRequest) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ModifyRequest_OneofMarshaler, _ModifyRequest_OneofUnmarshaler, _ModifyRequest_OneofSizer, []interface{}{
		(*ModifyRequest_ShowControl)(nil),
	}
}

func _ModifyRequest_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ModifyRequest)
	// ModifyRequestContent
	switch x := m.ModifyRequestContent.(type) {
	case *ModifyRequest_ShowControl:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ShowControl); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ModifyRequest.ModifyRequestContent has unexpected type %T", x)
	}
	return nil
}

func _ModifyRequest_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ModifyRequest)
	switch tag {
	case 2: // ModifyRequestContent.showControl
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ShowControl)
		err := b.DecodeMessage(msg)
		m.ModifyRequestContent = &ModifyRequest_ShowControl{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ModifyRequest_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ModifyRequest)
	// ModifyRequestContent
	switch x := m.ModifyRequestContent.(type) {
	case *ModifyRequest_ShowControl:
		s := proto.Size(x.ShowControl)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ModifyReply struct {
	PipelineName string `protobuf:"bytes,1,opt,name=pipelineName,proto3" json:"pipelineName,omitempty"`
	// Types that are valid to be assigned to ModifyReplyContent:
	//	*ModifyReply_Status
	ModifyReplyContent   isModifyReply_ModifyReplyContent `protobuf_oneof:"modifyReplyContent"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *ModifyReply) Reset()         { *m = ModifyReply{} }
func (m *ModifyReply) String() string { return proto.CompactTextString(m) }
func (*ModifyReply) ProtoMessage()    {}
func (*ModifyReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{19}
}
func (m *ModifyReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ModifyReply.Unmarshal(m, b)
}
func (m *ModifyReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ModifyReply.Marshal(b, m, deterministic)
}
func (dst *ModifyReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ModifyReply.Merge(dst, src)
}
func (m *ModifyReply) XXX_Size() int {
	return xxx_messageInfo_ModifyReply.Size(m)
}
func (m *ModifyReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ModifyReply.DiscardUnknown(m)
}

var xxx_messageInfo_ModifyReply proto.InternalMessageInfo

func (m *ModifyReply) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

type isModifyReply_ModifyReplyContent interface {
	isModifyReply_ModifyReplyContent()
}

type ModifyReply_Status struct {
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*ModifyReply_Status) isModifyReply_ModifyReplyContent() {}

func (m *ModifyReply) GetModifyReplyContent() isModifyReply_ModifyReplyContent {
	if m != nil {
		return m.ModifyReplyContent
	}
	return nil
}

func (m *ModifyReply) GetStatus() *Status {
	if x, ok := m.GetModifyReplyContent().(*ModifyReply_Status); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*ModifyReply) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _ModifyReply_OneofMarshaler, _ModifyReply_OneofUnmarshaler, _ModifyReply_OneofSizer, []interface{}{
		(*ModifyReply_Status)(nil),
	}
}

func _ModifyReply_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*ModifyReply)
	// modifyReplyContent
	switch x := m.ModifyReplyContent.(type) {
	case *ModifyReply_Status:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Status); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("ModifyReply.ModifyReplyContent has unexpected type %T", x)
	}
	return nil
}

func _ModifyReply_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*ModifyReply)
	switch tag {
	case 2: // modifyReplyContent.status
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Status)
		err := b.DecodeMessage(msg)
		m.ModifyReplyContent = &ModifyReply_Status{msg}
		return true, err
	default:
		return false, nil
	}
}

func _ModifyReply_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*ModifyReply)
	// modifyReplyContent
	switch x := m.ModifyReplyContent.(type) {
	case *ModifyReply_Status:
		s := proto.Size(x.Status)
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ShowControl struct {
	HandsUp              bool     `protobuf:"varint,1,opt,name=handsUp,proto3" json:"handsUp,omitempty"`
	StandUp              bool     `protobuf:"varint,2,opt,name=standUp,proto3" json:"standUp,omitempty"`
	TeacherPatorl        bool     `protobuf:"varint,3,opt,name=teacherPatorl,proto3" json:"teacherPatorl,omitempty"`
	ProbSolve            bool     `protobuf:"varint,4,opt,name=probSolve,proto3" json:"probSolve,omitempty"`
	HumanFace            bool     `protobuf:"varint,5,opt,name=humanFace,proto3" json:"humanFace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowControl) Reset()         { *m = ShowControl{} }
func (m *ShowControl) String() string { return proto.CompactTextString(m) }
func (*ShowControl) ProtoMessage()    {}
func (*ShowControl) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{20}
}
func (m *ShowControl) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowControl.Unmarshal(m, b)
}
func (m *ShowControl) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowControl.Marshal(b, m, deterministic)
}
func (dst *ShowControl) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowControl.Merge(dst, src)
}
func (m *ShowControl) XXX_Size() int {
	return xxx_messageInfo_ShowControl.Size(m)
}
func (m *ShowControl) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowControl.DiscardUnknown(m)
}

var xxx_messageInfo_ShowControl proto.InternalMessageInfo

func (m *ShowControl) GetHandsUp() bool {
	if m != nil {
		return m.HandsUp
	}
	return false
}

func (m *ShowControl) GetStandUp() bool {
	if m != nil {
		return m.StandUp
	}
	return false
}

func (m *ShowControl) GetTeacherPatorl() bool {
	if m != nil {
		return m.TeacherPatorl
	}
	return false
}

func (m *ShowControl) GetProbSolve() bool {
	if m != nil {
		return m.ProbSolve
	}
	return false
}

func (m *ShowControl) GetHumanFace() bool {
	if m != nil {
		return m.HumanFace
	}
	return false
}

type Status struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_28e7b72eb3b5d3d7, []int{21}
}
func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (dst *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(dst, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Status) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*PipelineRequest)(nil), "Lynxi.PipelineRequest")
	proto.RegisterType((*FrameExtractFrequency)(nil), "Lynxi.FrameExtractFrequency")
	proto.RegisterType((*PipelineReply)(nil), "Lynxi.PipelineReply")
	proto.RegisterType((*TaskRequest)(nil), "Lynxi.TaskRequest")
	proto.RegisterType((*SmartClassInfo)(nil), "Lynxi.SmartClassInfo")
	proto.RegisterType((*TaskReply)(nil), "Lynxi.TaskReply")
	proto.RegisterType((*StopRequest)(nil), "Lynxi.StopRequest")
	proto.RegisterType((*StopReply)(nil), "Lynxi.StopReply")
	proto.RegisterType((*SporadicStreamDataReply)(nil), "Lynxi.SporadicStreamDataReply")
	proto.RegisterType((*HandsUp)(nil), "Lynxi.HandsUp")
	proto.RegisterType((*StandUp)(nil), "Lynxi.StandUp")
	proto.RegisterType((*Patrol)(nil), "Lynxi.Patrol")
	proto.RegisterType((*ProbSolve)(nil), "Lynxi.ProbSolve")
	proto.RegisterType((*PeriodicStreamDataReply)(nil), "Lynxi.PeriodicStreamDataReply")
	proto.RegisterType((*AudioStreamDataReply)(nil), "Lynxi.AudioStreamDataReply")
	proto.RegisterType((*Emotion)(nil), "Lynxi.Emotion")
	proto.RegisterType((*Attention)(nil), "Lynxi.Attention")
	proto.RegisterType((*BBox)(nil), "Lynxi.BBox")
	proto.RegisterType((*ModifyRequest)(nil), "Lynxi.ModifyRequest")
	proto.RegisterType((*ModifyReply)(nil), "Lynxi.ModifyReply")
	proto.RegisterType((*ShowControl)(nil), "Lynxi.ShowControl")
	proto.RegisterType((*Status)(nil), "Lynxi.Status")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SmartClassClient is the client API for SmartClass service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SmartClassClient interface {
	// 启动一条 pipeline，可启动多条不同类型的 pipeline
	StartPipeline(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (SmartClass_StartPipelineClient, error)
	// 执行 pipeline 支持的各类的任务，以流的方式返回结果
	Exec(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (SmartClass_ExecClient, error)
	// 在运行期间修改 pipeline 的参数，例如：显示/隐藏举手提示，显示/隐藏起立提示
	Modify(ctx context.Context, opts ...grpc.CallOption) (SmartClass_ModifyClient, error)
	// 停止模块
	Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error)
}

type smartClassClient struct {
	cc *grpc.ClientConn
}

func NewSmartClassClient(cc *grpc.ClientConn) SmartClassClient {
	return &smartClassClient{cc}
}

func (c *smartClassClient) StartPipeline(ctx context.Context, in *PipelineRequest, opts ...grpc.CallOption) (SmartClass_StartPipelineClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SmartClass_serviceDesc.Streams[0], "/Lynxi.SmartClass/StartPipeline", opts...)
	if err != nil {
		return nil, err
	}
	x := &smartClassStartPipelineClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SmartClass_StartPipelineClient interface {
	Recv() (*PipelineReply, error)
	grpc.ClientStream
}

type smartClassStartPipelineClient struct {
	grpc.ClientStream
}

func (x *smartClassStartPipelineClient) Recv() (*PipelineReply, error) {
	m := new(PipelineReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *smartClassClient) Exec(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (SmartClass_ExecClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SmartClass_serviceDesc.Streams[1], "/Lynxi.SmartClass/Exec", opts...)
	if err != nil {
		return nil, err
	}
	x := &smartClassExecClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SmartClass_ExecClient interface {
	Recv() (*TaskReply, error)
	grpc.ClientStream
}

type smartClassExecClient struct {
	grpc.ClientStream
}

func (x *smartClassExecClient) Recv() (*TaskReply, error) {
	m := new(TaskReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *smartClassClient) Modify(ctx context.Context, opts ...grpc.CallOption) (SmartClass_ModifyClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SmartClass_serviceDesc.Streams[2], "/Lynxi.SmartClass/Modify", opts...)
	if err != nil {
		return nil, err
	}
	x := &smartClassModifyClient{stream}
	return x, nil
}

type SmartClass_ModifyClient interface {
	Send(*ModifyRequest) error
	CloseAndRecv() (*ModifyReply, error)
	grpc.ClientStream
}

type smartClassModifyClient struct {
	grpc.ClientStream
}

func (x *smartClassModifyClient) Send(m *ModifyRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *smartClassModifyClient) CloseAndRecv() (*ModifyReply, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ModifyReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *smartClassClient) Stop(ctx context.Context, in *StopRequest, opts ...grpc.CallOption) (*StopReply, error) {
	out := new(StopReply)
	err := c.cc.Invoke(ctx, "/Lynxi.SmartClass/Stop", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SmartClassServer is the server API for SmartClass service.
type SmartClassServer interface {
	// 启动一条 pipeline，可启动多条不同类型的 pipeline
	StartPipeline(*PipelineRequest, SmartClass_StartPipelineServer) error
	// 执行 pipeline 支持的各类的任务，以流的方式返回结果
	Exec(*TaskRequest, SmartClass_ExecServer) error
	// 在运行期间修改 pipeline 的参数，例如：显示/隐藏举手提示，显示/隐藏起立提示
	Modify(SmartClass_ModifyServer) error
	// 停止模块
	Stop(context.Context, *StopRequest) (*StopReply, error)
}

func RegisterSmartClassServer(s *grpc.Server, srv SmartClassServer) {
	s.RegisterService(&_SmartClass_serviceDesc, srv)
}

func _SmartClass_StartPipeline_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PipelineRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmartClassServer).StartPipeline(m, &smartClassStartPipelineServer{stream})
}

type SmartClass_StartPipelineServer interface {
	Send(*PipelineReply) error
	grpc.ServerStream
}

type smartClassStartPipelineServer struct {
	grpc.ServerStream
}

func (x *smartClassStartPipelineServer) Send(m *PipelineReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SmartClass_Exec_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SmartClassServer).Exec(m, &smartClassExecServer{stream})
}

type SmartClass_ExecServer interface {
	Send(*TaskReply) error
	grpc.ServerStream
}

type smartClassExecServer struct {
	grpc.ServerStream
}

func (x *smartClassExecServer) Send(m *TaskReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SmartClass_Modify_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SmartClassServer).Modify(&smartClassModifyServer{stream})
}

type SmartClass_ModifyServer interface {
	SendAndClose(*ModifyReply) error
	Recv() (*ModifyRequest, error)
	grpc.ServerStream
}

type smartClassModifyServer struct {
	grpc.ServerStream
}

func (x *smartClassModifyServer) SendAndClose(m *ModifyReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *smartClassModifyServer) Recv() (*ModifyRequest, error) {
	m := new(ModifyRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SmartClass_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SmartClassServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Lynxi.SmartClass/Stop",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SmartClassServer).Stop(ctx, req.(*StopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SmartClass_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Lynxi.SmartClass",
	HandlerType: (*SmartClassServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stop",
			Handler:    _SmartClass_Stop_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartPipeline",
			Handler:       _SmartClass_StartPipeline_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Exec",
			Handler:       _SmartClass_Exec_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Modify",
			Handler:       _SmartClass_Modify_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "lynxi.proto",
}

func init() { proto.RegisterFile("lynxi.proto", fileDescriptor_lynxi_28e7b72eb3b5d3d7) }

var fileDescriptor_lynxi_28e7b72eb3b5d3d7 = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xdb, 0x6e, 0xe3, 0x36,
	0x13, 0xb6, 0xe4, 0x53, 0x3c, 0x8a, 0xf3, 0x07, 0x84, 0xe3, 0x15, 0xf2, 0x07, 0xdb, 0x40, 0xe8,
	0xc1, 0x2d, 0x0a, 0x63, 0xa3, 0x05, 0xb6, 0x05, 0x7a, 0x15, 0xaf, 0x13, 0x38, 0x45, 0x5b, 0x18,
	0x74, 0x16, 0xbd, 0x66, 0x24, 0x26, 0x16, 0x56, 0x12, 0x55, 0x89, 0x4e, 0xad, 0xbb, 0x02, 0x7d,
	0x89, 0xde, 0xf7, 0x2d, 0x7a, 0xdf, 0xa7, 0xe8, 0x13, 0xf4, 0x2d, 0x0a, 0x52, 0xa4, 0x0e, 0x1b,
	0x67, 0xd3, 0x02, 0x45, 0xef, 0x34, 0xdf, 0x1c, 0xf8, 0xcd, 0x8c, 0x66, 0x48, 0xb0, 0xc2, 0x3c,
	0xde, 0x06, 0xd3, 0x24, 0x65, 0x9c, 0xa1, 0xee, 0x37, 0x42, 0x70, 0x7e, 0x37, 0xe0, 0x7f, 0xcb,
	0x20, 0xa1, 0x61, 0x10, 0x53, 0x4c, 0x7f, 0xd8, 0xd0, 0x8c, 0x23, 0x07, 0xf6, 0x13, 0x05, 0x7d,
	0x47, 0x22, 0x6a, 0x1b, 0xa7, 0xc6, 0x64, 0x80, 0x1b, 0x18, 0x7a, 0x0e, 0xe0, 0xd3, 0xfb, 0xc0,
	0xa3, 0x73, 0x9a, 0x79, 0xb6, 0x79, 0x6a, 0x4c, 0x86, 0xb8, 0x86, 0xa0, 0x6b, 0x38, 0xba, 0x4d,
	0x49, 0x44, 0x2f, 0xb6, 0x3c, 0x25, 0x1e, 0xbf, 0x4c, 0x45, 0xec, 0xd8, 0xcb, 0xed, 0xf6, 0xa9,
	0x31, 0xb1, 0xdc, 0x93, 0xa9, 0x3c, 0x7e, 0x7a, 0xb9, 0xcb, 0x66, 0xd1, 0xc2, 0xbb, 0x9d, 0x67,
	0x36, 0x8c, 0x93, 0x26, 0xd9, 0xd7, 0x2c, 0xe6, 0x34, 0xe6, 0xce, 0xf7, 0x70, 0xb4, 0x33, 0x16,
	0x42, 0xd0, 0x59, 0xb2, 0xac, 0x48, 0x62, 0x88, 0xe5, 0x37, 0x1a, 0x43, 0x6f, 0x4e, 0x39, 0xf5,
	0xb8, 0x22, 0xae, 0x24, 0x61, 0x7b, 0x49, 0x3c, 0x2a, 0x39, 0x0e, 0xb1, 0xfc, 0x76, 0x96, 0x30,
	0xac, 0xea, 0x93, 0x84, 0x39, 0xfa, 0x04, 0x7a, 0x19, 0x27, 0x7c, 0x93, 0xc9, 0x90, 0x96, 0x3b,
	0x54, 0xa9, 0xac, 0x24, 0xb8, 0x68, 0x61, 0xa5, 0x9e, 0x8d, 0x61, 0x94, 0xd4, 0x3d, 0x35, 0xd5,
	0x5f, 0x0c, 0xb0, 0xae, 0x49, 0xf6, 0x56, 0x97, 0x7b, 0x0c, 0x3d, 0x4e, 0xb2, 0xb7, 0x57, 0xbe,
	0xe2, 0xa8, 0xa4, 0x07, 0x6d, 0x30, 0x77, 0xb4, 0xe1, 0x0b, 0x80, 0x2c, 0x22, 0x29, 0x7f, 0x1d,
	0x92, 0x2c, 0x53, 0xb5, 0x3d, 0xd2, 0x84, 0x4a, 0xc5, 0x55, 0x7c, 0xcb, 0x16, 0x2d, 0x5c, 0x33,
	0x9d, 0x8d, 0x00, 0xf1, 0x8a, 0x83, 0xa6, 0xf6, 0x25, 0x1c, 0x34, 0xbd, 0xd0, 0xc7, 0x70, 0xe0,
	0xb1, 0xf8, 0x36, 0xb8, 0xbb, 0x0c, 0x42, 0xba, 0x24, 0x7c, 0xad, 0xfe, 0x86, 0x77, 0x50, 0xe7,
	0x27, 0x13, 0x06, 0x45, 0x52, 0xa2, 0x46, 0x8f, 0xa5, 0x34, 0x87, 0xfd, 0x2c, 0x61, 0x29, 0xf1,
	0x03, 0x6f, 0x4e, 0x38, 0x91, 0x29, 0x59, 0xee, 0x73, 0x4d, 0x58, 0xa9, 0x56, 0x3c, 0xa5, 0x24,
	0x12, 0x06, 0x32, 0xda, 0xa2, 0x85, 0x1b, 0x5e, 0x22, 0x4a, 0x42, 0xd3, 0x80, 0xe9, 0x28, 0xed,
	0x46, 0x94, 0xa5, 0x52, 0xed, 0x88, 0x52, 0xf7, 0x42, 0x5f, 0xc1, 0x80, 0x6c, 0xfc, 0x80, 0xc9,
	0x10, 0x1d, 0x19, 0xe2, 0xff, 0x2a, 0xc4, 0xb9, 0xc0, 0x1f, 0xfa, 0x57, 0xf6, 0x33, 0x04, 0x87,
	0x5c, 0x67, 0xab, 0x8b, 0x77, 0x05, 0xd6, 0x8a, 0xb3, 0xe4, 0x5f, 0x68, 0xab, 0xe3, 0xc2, 0xa0,
	0x08, 0x25, 0x8a, 0xf9, 0xd1, 0x7b, 0x7f, 0x38, 0xfd, 0xbb, 0x39, 0xbf, 0x99, 0xf0, 0xec, 0x91,
	0x0a, 0x0a, 0x2e, 0x1e, 0x89, 0xae, 0xfc, 0xad, 0x0c, 0xd1, 0xc5, 0x4a, 0x42, 0xc7, 0xb0, 0x27,
	0x07, 0x4d, 0x68, 0x4c, 0xa9, 0x29, 0x65, 0x74, 0x02, 0x03, 0x1e, 0x44, 0x74, 0xc5, 0x49, 0x94,
	0xc8, 0x12, 0xb7, 0x71, 0x05, 0xa0, 0x11, 0x74, 0x83, 0x88, 0xdc, 0x51, 0x59, 0xb9, 0x7d, 0x5c,
	0x08, 0x68, 0x02, 0xfd, 0x35, 0x89, 0xfd, 0xec, 0x4d, 0x62, 0x77, 0x25, 0xd7, 0x03, 0xc5, 0x75,
	0x51, 0xa0, 0x58, 0xab, 0x85, 0x65, 0xc6, 0x49, 0xec, 0xbf, 0x49, 0xec, 0x5e, 0xc3, 0x72, 0x55,
	0xa0, 0x58, 0xab, 0xd1, 0x4b, 0x18, 0x72, 0x4a, 0xbc, 0x35, 0x4d, 0x97, 0x84, 0xa7, 0x2c, 0xb4,
	0xfb, 0x8d, 0x2a, 0x14, 0x20, 0x6e, 0xda, 0xa0, 0x29, 0x0c, 0x92, 0x94, 0xdd, 0xac, 0x58, 0x78,
	0x4f, 0xed, 0x3d, 0xe9, 0x70, 0xa8, 0x1d, 0x34, 0x8e, 0x2b, 0x13, 0xe7, 0x33, 0xe8, 0x2b, 0x8a,
	0xe8, 0x03, 0xe8, 0xdc, 0xdc, 0x30, 0x51, 0xa9, 0xf6, 0xc4, 0x72, 0x2d, 0xe5, 0x35, 0x9b, 0xb1,
	0x2d, 0x96, 0x0a, 0x61, 0xab, 0x48, 0x3e, 0x6d, 0xfb, 0x29, 0xf4, 0x14, 0xa3, 0x27, 0x4d, 0x3f,
	0x87, 0x41, 0x49, 0xed, 0x69, 0xeb, 0x3f, 0x0c, 0x78, 0xf6, 0xc8, 0x9f, 0xfe, 0x5f, 0x76, 0x9b,
	0x46, 0x8c, 0x07, 0x2c, 0xb6, 0xbb, 0x92, 0xa7, 0xee, 0xe1, 0x45, 0x81, 0x62, 0xad, 0x16, 0xed,
	0x20, 0x5c, 0x0c, 0x89, 0xb0, 0xed, 0x49, 0x5b, 0xdd, 0x8e, 0x73, 0x8d, 0xe3, 0xca, 0xc4, 0x09,
	0x61, 0xb4, 0x6b, 0x06, 0x05, 0xcb, 0x8c, 0x93, 0x94, 0x5f, 0x07, 0xe5, 0xb5, 0x54, 0x01, 0xc8,
	0x86, 0x3e, 0x8d, 0x7d, 0xa9, 0x2b, 0x86, 0x4a, 0x8b, 0xd2, 0x8f, 0x6d, 0x62, 0xff, 0x3a, 0x4f,
	0x8a, 0xed, 0x2e, 0xfc, 0x34, 0xe0, 0xcc, 0xa1, 0xaf, 0x18, 0xd7, 0xea, 0x6e, 0xec, 0xac, 0xbb,
	0x3c, 0x43, 0xe5, 0xac, 0xcf, 0x28, 0x44, 0xe7, 0x6b, 0x18, 0x94, 0xb9, 0x3c, 0x1d, 0xe7, 0xa4,
	0x5e, 0x91, 0x22, 0x52, 0x2d, 0xff, 0x7b, 0xe8, 0x08, 0x5b, 0xd1, 0xb1, 0xc0, 0x17, 0x18, 0xcf,
	0x55, 0xba, 0xa5, 0x2c, 0x2e, 0xab, 0xb8, 0xda, 0x1f, 0xf2, 0x1b, 0x1d, 0x80, 0xb9, 0x3d, 0x93,
	0x09, 0x76, 0xb1, 0xb9, 0x3d, 0x13, 0x72, 0x7e, 0x26, 0x9b, 0xd6, 0xc5, 0x66, 0x2e, 0xe5, 0xad,
	0x2b, 0x47, 0x53, 0xe8, 0x5d, 0xa9, 0x77, 0xe5, 0x00, 0x0a, 0xbd, 0xeb, 0xfc, 0x6c, 0xc0, 0xf0,
	0x5b, 0xe6, 0x07, 0xb7, 0xf9, 0x3f, 0x79, 0x0b, 0xbc, 0x02, 0x2b, 0x5b, 0xb3, 0x1f, 0xc5, 0x1e,
	0x14, 0xf3, 0x59, 0x2c, 0x75, 0xa4, 0xe7, 0xb9, 0xd2, 0x2c, 0x5a, 0xb8, 0x6e, 0x28, 0x2e, 0xc8,
	0xc6, 0x61, 0x7a, 0x91, 0x26, 0x60, 0x69, 0x5c, 0x34, 0xfd, 0xef, 0x50, 0xa8, 0x2e, 0x65, 0xf3,
	0xfd, 0x97, 0xf2, 0x08, 0x50, 0x54, 0xc5, 0xd6, 0x27, 0xfe, 0x6a, 0x80, 0x55, 0x23, 0x2a, 0xba,
	0xac, 0xf7, 0x98, 0x38, 0x6d, 0xaf, 0xda, 0x5b, 0x76, 0xb5, 0xb7, 0xcc, 0x42, 0xa3, 0xf7, 0xd4,
	0x87, 0xf5, 0x3d, 0xc5, 0xd2, 0x50, 0xb6, 0x61, 0x0f, 0x37, 0x41, 0xd1, 0xf7, 0x6a, 0x31, 0x75,
	0xa4, 0x45, 0x05, 0x08, 0xed, 0x7a, 0x13, 0x91, 0x58, 0xbe, 0x42, 0xba, 0x85, 0xb6, 0x04, 0x9c,
	0x29, 0xf4, 0x8a, 0x7c, 0x44, 0xef, 0x3d, 0xe6, 0x53, 0x35, 0xdf, 0xf2, 0x1b, 0x1d, 0x42, 0x3b,
	0xca, 0xee, 0xd4, 0xef, 0x20, 0x3e, 0xdd, 0x3f, 0x0d, 0x80, 0xea, 0x3a, 0x47, 0xe7, 0x30, 0x5c,
	0x89, 0x59, 0xd1, 0xcf, 0x19, 0x34, 0xd6, 0x1b, 0xb1, 0xf9, 0xa4, 0x3a, 0x1e, 0x3d, 0xc0, 0x93,
	0x30, 0x77, 0x5a, 0x2f, 0x0c, 0xf4, 0x02, 0x3a, 0x17, 0x5b, 0xea, 0x21, 0xdd, 0xdc, 0xda, 0x33,
	0xe6, 0xf8, 0xb0, 0x81, 0x69, 0x8f, 0x57, 0xd0, 0x2b, 0x7a, 0x89, 0x74, 0xd4, 0x46, 0xcb, 0x8f,
	0xd1, 0x3b, 0xa8, 0xf4, 0x9b, 0x18, 0x68, 0x0a, 0x1d, 0x71, 0x03, 0x96, 0x27, 0xd5, 0x6e, 0xd6,
	0xf2, 0xa4, 0xf2, 0x8a, 0x74, 0x5a, 0x37, 0x3d, 0xf9, 0xaa, 0x7d, 0xf9, 0x57, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x23, 0xb6, 0x1f, 0xd1, 0xe4, 0x0a, 0x00, 0x00,
}
