// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lynxi_nesting.proto

package var_length

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_b0f83fb4f3a44d23, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 不能使用int, 只能使用int32这种.
// 1, 2, 3表示顺序.
// repeated Bbox bbox = 2;
type HelloReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bbox                 *Bbox    `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Sbox                 *Ss      `protobuf:"bytes,3,opt,name=sbox,proto3" json:"sbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_b0f83fb4f3a44d23, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloReply) GetBbox() *Bbox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *HelloReply) GetSbox() *Ss {
	if m != nil {
		return m.Sbox
	}
	return nil
}

type Bbox struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W                    int32    `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32    `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bbox) Reset()         { *m = Bbox{} }
func (m *Bbox) String() string { return proto.CompactTextString(m) }
func (*Bbox) ProtoMessage()    {}
func (*Bbox) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_b0f83fb4f3a44d23, []int{2}
}
func (m *Bbox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bbox.Unmarshal(m, b)
}
func (m *Bbox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bbox.Marshal(b, m, deterministic)
}
func (dst *Bbox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bbox.Merge(dst, src)
}
func (m *Bbox) XXX_Size() int {
	return xxx_messageInfo_Bbox.Size(m)
}
func (m *Bbox) XXX_DiscardUnknown() {
	xxx_messageInfo_Bbox.DiscardUnknown(m)
}

var xxx_messageInfo_Bbox proto.InternalMessageInfo

func (m *Bbox) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Bbox) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Bbox) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Bbox) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

type Ss struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ss) Reset()         { *m = Ss{} }
func (m *Ss) String() string { return proto.CompactTextString(m) }
func (*Ss) ProtoMessage()    {}
func (*Ss) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_b0f83fb4f3a44d23, []int{3}
}
func (m *Ss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ss.Unmarshal(m, b)
}
func (m *Ss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ss.Marshal(b, m, deterministic)
}
func (dst *Ss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ss.Merge(dst, src)
}
func (m *Ss) XXX_Size() int {
	return xxx_messageInfo_Ss.Size(m)
}
func (m *Ss) XXX_DiscardUnknown() {
	xxx_messageInfo_Ss.DiscardUnknown(m)
}

var xxx_messageInfo_Ss proto.InternalMessageInfo

func (m *Ss) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *Ss) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "var_length.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "var_length.HelloReply")
	proto.RegisterType((*Bbox)(nil), "var_length.Bbox")
	proto.RegisterType((*Ss)(nil), "var_length.Ss")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// ① 简单rpc.
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	// ② 应答式流rpc.
	LstSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_LstSayHelloClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/var_length.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) LstSayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_LstSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/var_length.Greeter/LstSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterLstSayHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_LstSayHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterLstSayHelloClient struct {
	grpc.ClientStream
}

func (x *greeterLstSayHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// ① 简单rpc.
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	// ② 应答式流rpc.
	LstSayHello(*HelloRequest, Greeter_LstSayHelloServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/var_length.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_LstSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).LstSayHello(m, &greeterLstSayHelloServer{stream})
}

type Greeter_LstSayHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterLstSayHelloServer struct {
	grpc.ServerStream
}

func (x *greeterLstSayHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "var_length.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LstSayHello",
			Handler:       _Greeter_LstSayHello_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lynxi_nesting.proto",
}

func init() { proto.RegisterFile("lynxi_nesting.proto", fileDescriptor_lynxi_nesting_b0f83fb4f3a44d23) }

var fileDescriptor_lynxi_nesting_b0f83fb4f3a44d23 = []byte{
	// 293 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x9b, 0x00, 0xb9, 0x56, 0x80, 0x8c, 0x84, 0x22, 0x58, 0x22, 0x8b, 0xa1, 0x93,
	0x85, 0x8a, 0xc4, 0xd8, 0x21, 0x0c, 0x74, 0xe8, 0x50, 0x39, 0x43, 0xc7, 0x2a, 0x01, 0x2b, 0x09,
	0x72, 0xe3, 0x60, 0x1b, 0x12, 0xff, 0x09, 0x7e, 0x04, 0xbf, 0x14, 0xd9, 0x20, 0x35, 0x48, 0xdd,
	0xd8, 0xee, 0xe9, 0x7d, 0xef, 0x5d, 0xe2, 0x83, 0x4b, 0x61, 0x9b, 0xbe, 0xde, 0x36, 0x5c, 0x9b,
	0xba, 0x29, 0x69, 0xab, 0xa4, 0x91, 0x18, 0x3e, 0x72, 0xb5, 0x15, 0xbc, 0x29, 0x4d, 0x45, 0x08,
	0x4c, 0x97, 0x5c, 0x08, 0xc9, 0xf8, 0xdb, 0x3b, 0xd7, 0x06, 0x63, 0x08, 0x9a, 0x7c, 0xc7, 0x63,
	0x94, 0xa0, 0x59, 0xc4, 0xfc, 0x4c, 0x5e, 0x01, 0x7e, 0x99, 0x56, 0xd8, 0x43, 0x04, 0xbe, 0x85,
	0xa0, 0x28, 0x64, 0x1f, 0x8f, 0x12, 0x34, 0x9b, 0xcc, 0x2f, 0xe8, 0x7e, 0x01, 0x4d, 0x0b, 0xd9,
	0x33, 0xef, 0x62, 0x02, 0x81, 0x76, 0xd4, 0xd8, 0x53, 0x67, 0x43, 0x2a, 0xd3, 0xcc, 0x7b, 0x64,
	0x01, 0x81, 0x4b, 0xe0, 0x29, 0xa0, 0xde, 0xaf, 0x08, 0x19, 0xf2, 0xca, 0xfa, 0xf2, 0x90, 0x21,
	0xeb, 0x54, 0xe7, 0x4b, 0x42, 0x86, 0x3a, 0xa7, 0xaa, 0x38, 0xf8, 0x51, 0x15, 0x49, 0x60, 0x94,
	0xe9, 0x7d, 0x3a, 0xfa, 0x93, 0x8e, 0x18, 0xb2, 0xf3, 0x4f, 0x04, 0x27, 0x4f, 0x8a, 0x73, 0xc3,
	0x15, 0x5e, 0xc0, 0x69, 0x96, 0x5b, 0xff, 0x73, 0x38, 0x1e, 0x7e, 0xcf, 0xf0, 0x4d, 0xae, 0xaf,
	0x0e, 0x38, 0xad, 0xb0, 0xe4, 0x08, 0x3f, 0xc2, 0x64, 0xa5, 0xcd, 0x7f, 0x2a, 0xee, 0x50, 0xfa,
	0x00, 0x37, 0xb5, 0xa4, 0xa5, 0x6a, 0x9f, 0x29, 0xef, 0xf3, 0x5d, 0x2b, 0xb8, 0xa6, 0x95, 0x43,
	0x3a, 0xa9, 0xc4, 0x4b, 0x7a, 0xee, 0xf1, 0x8d, 0x9b, 0xd7, 0xee, 0x7c, 0x6b, 0xf4, 0x35, 0x1a,
	0x2f, 0x57, 0x9b, 0xe2, 0xd8, 0x5f, 0xf3, 0xfe, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x44, 0xfb, 0x81,
	0xd4, 0xe4, 0x01, 0x00, 0x00,
}
