// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lynxi_nesting.proto

package var_length

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_737aff7bb4aa0552, []int{0}
}
func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (dst *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(dst, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// 不能使用int, 只能使用int32这种.
// 1, 2, 3表示顺序.
// repeated Bbox bbox = 2;
type HelloReply struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Bbox                 *Bbox    `protobuf:"bytes,2,opt,name=bbox,proto3" json:"bbox,omitempty"`
	Sbox                 *Ss      `protobuf:"bytes,3,opt,name=sbox,proto3" json:"sbox,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_737aff7bb4aa0552, []int{1}
}
func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (dst *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(dst, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *HelloReply) GetBbox() *Bbox {
	if m != nil {
		return m.Bbox
	}
	return nil
}

func (m *HelloReply) GetSbox() *Ss {
	if m != nil {
		return m.Sbox
	}
	return nil
}

type Bbox struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	W                    int32    `protobuf:"varint,3,opt,name=w,proto3" json:"w,omitempty"`
	H                    int32    `protobuf:"varint,4,opt,name=h,proto3" json:"h,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Bbox) Reset()         { *m = Bbox{} }
func (m *Bbox) String() string { return proto.CompactTextString(m) }
func (*Bbox) ProtoMessage()    {}
func (*Bbox) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_737aff7bb4aa0552, []int{2}
}
func (m *Bbox) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Bbox.Unmarshal(m, b)
}
func (m *Bbox) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Bbox.Marshal(b, m, deterministic)
}
func (dst *Bbox) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Bbox.Merge(dst, src)
}
func (m *Bbox) XXX_Size() int {
	return xxx_messageInfo_Bbox.Size(m)
}
func (m *Bbox) XXX_DiscardUnknown() {
	xxx_messageInfo_Bbox.DiscardUnknown(m)
}

var xxx_messageInfo_Bbox proto.InternalMessageInfo

func (m *Bbox) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *Bbox) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *Bbox) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func (m *Bbox) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

type Ss struct {
	X                    string   `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    string   `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Ss) Reset()         { *m = Ss{} }
func (m *Ss) String() string { return proto.CompactTextString(m) }
func (*Ss) ProtoMessage()    {}
func (*Ss) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_nesting_737aff7bb4aa0552, []int{3}
}
func (m *Ss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Ss.Unmarshal(m, b)
}
func (m *Ss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Ss.Marshal(b, m, deterministic)
}
func (dst *Ss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Ss.Merge(dst, src)
}
func (m *Ss) XXX_Size() int {
	return xxx_messageInfo_Ss.Size(m)
}
func (m *Ss) XXX_DiscardUnknown() {
	xxx_messageInfo_Ss.DiscardUnknown(m)
}

var xxx_messageInfo_Ss proto.InternalMessageInfo

func (m *Ss) GetX() string {
	if m != nil {
		return m.X
	}
	return ""
}

func (m *Ss) GetY() string {
	if m != nil {
		return m.Y
	}
	return ""
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "var_length.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "var_length.HelloReply")
	proto.RegisterType((*Bbox)(nil), "var_length.Bbox")
	proto.RegisterType((*Ss)(nil), "var_length.Ss")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	StreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_StreamSayHelloClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) StreamSayHello(ctx context.Context, opts ...grpc.CallOption) (Greeter_StreamSayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/var_length.Greeter/StreamSayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterStreamSayHelloClient{stream}
	return x, nil
}

type Greeter_StreamSayHelloClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterStreamSayHelloClient struct {
	grpc.ClientStream
}

func (x *greeterStreamSayHelloClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterStreamSayHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	StreamSayHello(Greeter_StreamSayHelloServer) error
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_StreamSayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).StreamSayHello(&greeterStreamSayHelloServer{stream})
}

type Greeter_StreamSayHelloServer interface {
	Send(*HelloReply) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterStreamSayHelloServer struct {
	grpc.ServerStream
}

func (x *greeterStreamSayHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterStreamSayHelloServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "var_length.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamSayHello",
			Handler:       _Greeter_StreamSayHello_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "lynxi_nesting.proto",
}

func init() { proto.RegisterFile("lynxi_nesting.proto", fileDescriptor_lynxi_nesting_737aff7bb4aa0552) }

var fileDescriptor_lynxi_nesting_737aff7bb4aa0552 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x71, 0x9b, 0x82, 0x7a, 0x54, 0x05, 0x19, 0x09, 0x45, 0xb0, 0x54, 0x16, 0x43, 0x27,
	0x0b, 0x15, 0x89, 0x91, 0x21, 0x0b, 0x19, 0x18, 0x2a, 0x67, 0xe8, 0x58, 0x25, 0x70, 0x4a, 0x82,
	0x9c, 0x38, 0xd8, 0x86, 0xc4, 0x7f, 0x87, 0x5f, 0x8a, 0x6c, 0x90, 0x1a, 0xa4, 0x6e, 0xf7, 0xf4,
	0xbe, 0x77, 0x67, 0xdf, 0xc1, 0x95, 0x74, 0xed, 0x50, 0xef, 0x5b, 0x34, 0xb6, 0x6e, 0x4b, 0xde,
	0x69, 0x65, 0x15, 0x85, 0xaf, 0x5c, 0xef, 0x25, 0xb6, 0xa5, 0xad, 0x18, 0x83, 0x45, 0x8a, 0x52,
	0x2a, 0x81, 0x1f, 0x9f, 0x68, 0x2c, 0xa5, 0x10, 0xb5, 0x79, 0x83, 0x31, 0x59, 0x91, 0xf5, 0x5c,
	0x84, 0x9a, 0xbd, 0x03, 0xfc, 0x31, 0x9d, 0x74, 0xc7, 0x08, 0x7a, 0x07, 0x51, 0x51, 0xa8, 0x21,
	0x9e, 0xac, 0xc8, 0xfa, 0x7c, 0x73, 0xc9, 0x0f, 0x03, 0x78, 0x52, 0xa8, 0x41, 0x04, 0x97, 0x32,
	0x88, 0x8c, 0xa7, 0xa6, 0x81, 0x5a, 0x8e, 0xa9, 0xcc, 0x88, 0xe0, 0xb1, 0x27, 0x88, 0x7c, 0x82,
	0x2e, 0x80, 0x0c, 0x61, 0xc4, 0x4c, 0x90, 0xa0, 0x5c, 0x68, 0x3e, 0x13, 0xc4, 0x79, 0xd5, 0x87,
	0x26, 0x33, 0x41, 0x7a, 0xaf, 0xaa, 0x38, 0xfa, 0x55, 0x15, 0x5b, 0xc1, 0x24, 0x33, 0x87, 0xf4,
	0xfc, 0x5f, 0x7a, 0x2e, 0x88, 0xdb, 0x64, 0x70, 0xf6, 0xac, 0x11, 0x2d, 0x6a, 0x9a, 0xc2, 0x32,
	0xb3, 0x1a, 0xf3, 0x26, 0xcb, 0x5d, 0xf8, 0x21, 0x8d, 0xc7, 0x8f, 0x1a, 0x2f, 0xe6, 0xe6, 0xfa,
	0x88, 0xd3, 0x49, 0xc7, 0x4e, 0xd6, 0xe4, 0x9e, 0x24, 0x8f, 0x70, 0x5b, 0x2b, 0x5e, 0xea, 0xee,
	0x95, 0xe3, 0x90, 0x37, 0x9d, 0x44, 0xc3, 0x2b, 0x0f, 0xf5, 0x4a, 0xcb, 0xb7, 0xe4, 0x22, 0x04,
	0x76, 0xbe, 0xde, 0xfa, 0x13, 0x6c, 0xc9, 0xf7, 0x64, 0x9a, 0xbe, 0xec, 0x8a, 0xd3, 0x70, 0x91,
	0x87, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x62, 0x8f, 0x4b, 0xa8, 0x01, 0x00, 0x00,
}
