// Code generated by protoc-gen-go. DO NOT EDIT.
// source: lynxi.proto

package lynxi

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TaskRequest struct {
	TaskId               uint32   `protobuf:"varint,1,opt,name=taskId,proto3" json:"taskId,omitempty"`
	PipelineName         string   `protobuf:"bytes,2,opt,name=pipelineName,proto3" json:"pipelineName,omitempty"`
	Uuid                 string   `protobuf:"bytes,3,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Rawinput             []byte   `protobuf:"bytes,4,opt,name=rawinput,proto3" json:"rawinput,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskRequest) Reset()         { *m = TaskRequest{} }
func (m *TaskRequest) String() string { return proto.CompactTextString(m) }
func (*TaskRequest) ProtoMessage()    {}
func (*TaskRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_cd3ce25fffab2b8c, []int{0}
}
func (m *TaskRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskRequest.Unmarshal(m, b)
}
func (m *TaskRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskRequest.Marshal(b, m, deterministic)
}
func (dst *TaskRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskRequest.Merge(dst, src)
}
func (m *TaskRequest) XXX_Size() int {
	return xxx_messageInfo_TaskRequest.Size(m)
}
func (m *TaskRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TaskRequest proto.InternalMessageInfo

func (m *TaskRequest) GetTaskId() uint32 {
	if m != nil {
		return m.TaskId
	}
	return 0
}

func (m *TaskRequest) GetPipelineName() string {
	if m != nil {
		return m.PipelineName
	}
	return ""
}

func (m *TaskRequest) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *TaskRequest) GetRawinput() []byte {
	if m != nil {
		return m.Rawinput
	}
	return nil
}

type ImageFeatureExtractReply struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Rawbboxraw           *BboxRaw `protobuf:"bytes,2,opt,name=Rawbboxraw,proto3" json:"Rawbboxraw,omitempty"`
	Feature              []string `protobuf:"bytes,3,rep,name=feature,proto3" json:"feature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ImageFeatureExtractReply) Reset()         { *m = ImageFeatureExtractReply{} }
func (m *ImageFeatureExtractReply) String() string { return proto.CompactTextString(m) }
func (*ImageFeatureExtractReply) ProtoMessage()    {}
func (*ImageFeatureExtractReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_cd3ce25fffab2b8c, []int{1}
}
func (m *ImageFeatureExtractReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImageFeatureExtractReply.Unmarshal(m, b)
}
func (m *ImageFeatureExtractReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImageFeatureExtractReply.Marshal(b, m, deterministic)
}
func (dst *ImageFeatureExtractReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImageFeatureExtractReply.Merge(dst, src)
}
func (m *ImageFeatureExtractReply) XXX_Size() int {
	return xxx_messageInfo_ImageFeatureExtractReply.Size(m)
}
func (m *ImageFeatureExtractReply) XXX_DiscardUnknown() {
	xxx_messageInfo_ImageFeatureExtractReply.DiscardUnknown(m)
}

var xxx_messageInfo_ImageFeatureExtractReply proto.InternalMessageInfo

func (m *ImageFeatureExtractReply) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *ImageFeatureExtractReply) GetRawbboxraw() *BboxRaw {
	if m != nil {
		return m.Rawbboxraw
	}
	return nil
}

func (m *ImageFeatureExtractReply) GetFeature() []string {
	if m != nil {
		return m.Feature
	}
	return nil
}

type BboxRaw struct {
	X                    int32    `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y                    int32    `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	H                    int32    `protobuf:"varint,3,opt,name=h,proto3" json:"h,omitempty"`
	W                    int32    `protobuf:"varint,4,opt,name=w,proto3" json:"w,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BboxRaw) Reset()         { *m = BboxRaw{} }
func (m *BboxRaw) String() string { return proto.CompactTextString(m) }
func (*BboxRaw) ProtoMessage()    {}
func (*BboxRaw) Descriptor() ([]byte, []int) {
	return fileDescriptor_lynxi_cd3ce25fffab2b8c, []int{2}
}
func (m *BboxRaw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BboxRaw.Unmarshal(m, b)
}
func (m *BboxRaw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BboxRaw.Marshal(b, m, deterministic)
}
func (dst *BboxRaw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BboxRaw.Merge(dst, src)
}
func (m *BboxRaw) XXX_Size() int {
	return xxx_messageInfo_BboxRaw.Size(m)
}
func (m *BboxRaw) XXX_DiscardUnknown() {
	xxx_messageInfo_BboxRaw.DiscardUnknown(m)
}

var xxx_messageInfo_BboxRaw proto.InternalMessageInfo

func (m *BboxRaw) GetX() int32 {
	if m != nil {
		return m.X
	}
	return 0
}

func (m *BboxRaw) GetY() int32 {
	if m != nil {
		return m.Y
	}
	return 0
}

func (m *BboxRaw) GetH() int32 {
	if m != nil {
		return m.H
	}
	return 0
}

func (m *BboxRaw) GetW() int32 {
	if m != nil {
		return m.W
	}
	return 0
}

func init() {
	proto.RegisterType((*TaskRequest)(nil), "lynxi.TaskRequest")
	proto.RegisterType((*ImageFeatureExtractReply)(nil), "lynxi.ImageFeatureExtractReply")
	proto.RegisterType((*BboxRaw)(nil), "lynxi.BboxRaw")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FaceClient is the client API for Face service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FaceClient interface {
	// 最基本的形式.
	FaceData(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*ImageFeatureExtractReply, error)
}

type faceClient struct {
	cc *grpc.ClientConn
}

func NewFaceClient(cc *grpc.ClientConn) FaceClient {
	return &faceClient{cc}
}

func (c *faceClient) FaceData(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*ImageFeatureExtractReply, error) {
	out := new(ImageFeatureExtractReply)
	err := c.cc.Invoke(ctx, "/lynxi.Face/FaceData", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaceServer is the server API for Face service.
type FaceServer interface {
	// 最基本的形式.
	FaceData(context.Context, *TaskRequest) (*ImageFeatureExtractReply, error)
}

func RegisterFaceServer(s *grpc.Server, srv FaceServer) {
	s.RegisterService(&_Face_serviceDesc, srv)
}

func _Face_FaceData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaceServer).FaceData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lynxi.Face/FaceData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaceServer).FaceData(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Face_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lynxi.Face",
	HandlerType: (*FaceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FaceData",
			Handler:    _Face_FaceData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lynxi.proto",
}

func init() { proto.RegisterFile("lynxi.proto", fileDescriptor_lynxi_cd3ce25fffab2b8c) }

var fileDescriptor_lynxi_cd3ce25fffab2b8c = []byte{
	// 278 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x3f, 0x6f, 0xb3, 0x30,
	0x10, 0x87, 0x5f, 0xbf, 0x09, 0xf9, 0x73, 0xd0, 0x0e, 0x37, 0x54, 0x56, 0x96, 0x22, 0x26, 0x26,
	0x86, 0xf4, 0x13, 0xa4, 0x6a, 0x23, 0xb1, 0x74, 0x38, 0xf5, 0x0b, 0x1c, 0x89, 0xdb, 0xa0, 0x10,
	0xa0, 0x60, 0x64, 0xf3, 0xed, 0x2b, 0x1c, 0x1a, 0xd1, 0xa1, 0x93, 0xfd, 0x9c, 0xed, 0x9f, 0xef,
	0xb1, 0xc1, 0x2f, 0xfa, 0xd2, 0xe6, 0x49, 0xdd, 0x54, 0xba, 0x42, 0xcf, 0x41, 0xd4, 0x83, 0xff,
	0xce, 0xed, 0x99, 0xd4, 0x57, 0xa7, 0x5a, 0x8d, 0x0f, 0xb0, 0xd0, 0xdc, 0x9e, 0xd3, 0xa3, 0x14,
	0xa1, 0x88, 0xef, 0x68, 0x24, 0x8c, 0x20, 0xa8, 0xf3, 0x5a, 0x15, 0x79, 0xa9, 0xde, 0xf8, 0xa2,
	0xe4, 0xff, 0x50, 0xc4, 0x6b, 0xfa, 0x55, 0x43, 0x84, 0x79, 0xd7, 0xe5, 0x47, 0x39, 0x73, 0x6b,
	0x6e, 0x8e, 0x1b, 0x58, 0x35, 0x6c, 0xf2, 0xb2, 0xee, 0xb4, 0x9c, 0x87, 0x22, 0x0e, 0xe8, 0xc6,
	0x91, 0x05, 0x99, 0x5e, 0xf8, 0x53, 0xed, 0x15, 0xeb, 0xae, 0x51, 0xaf, 0x56, 0x37, 0x7c, 0xd0,
	0xa4, 0xea, 0xa2, 0xbf, 0x65, 0x89, 0x49, 0x56, 0x02, 0x40, 0x6c, 0xb2, 0xac, 0xb2, 0x0d, 0x1b,
	0xd7, 0x81, 0xbf, 0xbd, 0x4f, 0xae, 0x4e, 0xcf, 0x59, 0x65, 0x89, 0x0d, 0x4d, 0x76, 0xa0, 0x84,
	0xe5, 0xc7, 0x35, 0x5a, 0xce, 0xc2, 0x59, 0xbc, 0xa6, 0x1f, 0x8c, 0x76, 0xb0, 0x1c, 0x0f, 0x60,
	0x00, 0xc2, 0xba, 0x5b, 0x3c, 0x12, 0x76, 0xa0, 0xde, 0x25, 0x7b, 0x24, 0xfa, 0x81, 0x4e, 0xce,
	0xc6, 0x23, 0x71, 0x1a, 0xc8, 0x38, 0x07, 0x8f, 0x84, 0xd9, 0xa6, 0x30, 0xdf, 0xf3, 0x41, 0xe1,
	0x0e, 0x56, 0xc3, 0xf8, 0xc2, 0x9a, 0x11, 0xc7, 0x66, 0x26, 0x0f, 0xba, 0x79, 0x1c, 0x6b, 0x7f,
	0x99, 0x46, 0xff, 0xb2, 0x85, 0xfb, 0x90, 0xa7, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0x7e,
	0xad, 0x02, 0x9f, 0x01, 0x00, 0x00,
}
